# a5.py

#
# Write the full name, SFU ID number, and SFU email of each member of your team:
# Name: Paavan Randhawa
# SFU ID number: 301614138
# SFU email: pkr14@sfu.ca


#
# The TA will run your program by calling the main() function. Inside main() put
# whatever code you need for your program to run. It should only be one or two
# lines of code.
#
import random, time

print('-'*12)
print('| POCOLOCO |')
print('-'*12)
instructions = input('Would you like to read the instructions?')
if instructions.lower().strip('!') in ['yes','yup','yeah','sure','y']:
    print("""Here are the instructions:\n 
      You, and three other players will start with a certain number of chips 
      and take turns rolling a dice. The goal of the game is to lose all of 
      your chips first. In each round, each player will roll three dice, and
      try to get the highest score possible. Poco (rolling [4,5,6]) is the 
      highest score possible and rewards you with 1300 points qne three of a 
      kind (e.g. [1,1,1] or [3,3,3]) is the second highest and rewards you with
      1000 times the number you rolled (e.g. [2,2,2] rewards you with 2000 points 
      and [5,5,5] rewards you with 5000 points). The third highest score is loco,
      and is a result of rolling [1,2,3] and rewards you with 900. All other rolls 
      are considered regular rolls and are ranked as shown below: \n
      You will add the numbers you rolled using the following points system:
      1 = 100 points 
      2 = 2 points 
      3 = 3 points 
      4 = 4 points 
      5 = 5 points 
      6 = 60 points \n
      For example, if you roll [1,6,5], your score will be 165 (100+60+5). At the start of each 
      round, the order that the players will roll in will be randomly generated by the computer.
     The first player will roll, and have the choice to roll a maximum of three times. 
     Each round, next player can, at most, roll as many times as the player before them. 
     At the end of the round, when everyone has finished rolling, the scores will be 
     calculated, and the winner and loser will be determined. Then, everyone except for the 
    loser will give chips to loser as shown below:\n
      1 chip if the winners score is a total of points 
      2 chips if the winners score is a loco 
      3 chips if the winners score is a three-of-a-kind 
      4 chips if the winners score is a poco \n
      Then, if no one has zero chips, another round will be played. The game will continue
     until someone runs out of chips. The first player to run out of all their chips 
     is the winner. In case of a tie, at any point, the computer will randomly 
     choose a winner. \n
       
      """)
    player_name = input("What is your name?")
    chips = int(input(f"""Hello {player_name}! How many chips would you like to start with?"""))
else:
    player_name = input("What is your name?")
    chips = int(input(f"""Hello {player_name}! How many chips would you like to start with?"""))
    





player_chips = chips
computer1_chips = chips
computer2_chips = chips
computer3_chips = chips

chip_count = {
    player_name: player_chips,
    "computer1": computer1_chips,
    "computer2": computer2_chips,
    "computer3": computer3_chips,
}

dice_dict = {
    1:'''
---------
|       |
|   o   |
|       |
---------''',
 2:'''
---------
| o     |
|       |
|     o |
 ---------''',
 3:'''
---------
| o     |
|   o   |
|     o |
---------''',
 4:'''
---------
| o   o |
|       |
| o   o |
---------''',
 5:'''
---------
| o   o |
|   o   |
| o   o |
---------''',
 6:'''
---------
| o   o |
| o   o |
| o   o |
---------''',
 
}

def print_dice(roll_dice):
    
    item1 = dice_dict[roll_dice[0]].strip().split("\n")
    item2 = dice_dict[roll_dice[1]].strip().split("\n")
    item3 = dice_dict[roll_dice[2]].strip().split("\n")

    for row in zip(item1, item2, item3):
        print(row[0] + " " + row[1] + " " + row[2])


def choose_order():
    players = [player_name, "computer1", "computer2", "computer3"]
    order = []
    for item in range(0, len(players)):
        x = random.choice(players)
        order.append(x)
        players.remove(x)
    first_player = order[0]
    second_player = order[1]
    third_player = order[2]
    fourth_player = order[3]
    print(
        f"""Here is the order you and the three other players will play in:
          1. {order[0]}
          2. {order[1]}
          3. {order[2]}
          4. {order[3]}"""
    )
    return first_player, second_player, third_player, fourth_player


def random_dice_combination():
    original_roll = []
    for item in range(0, 3):
        random_roll = random.randint(1, 6)
        original_roll.append(random_roll)
    roll = sorted(original_roll)
    return roll


def calculate_score(roll):
    points_list = []
    regular_points = [2, 3, 4, 5]
    for item in roll:
        if item == 1:
            points = 100
            points_list.append(points)
        elif item in regular_points:
            points = item
            points_list.append(points)
        elif item == 6:
            points = 60
            points_list.append(points)
    return sum(points_list)


def analyze_roll(roll):
    poco = [4, 5, 6]
    loco = [1, 2, 3]
    three_of_a_kind = True
    for item in range(0, len(roll)):
        if roll[item] != roll[0]:
            three_of_a_kind = False
    if roll == poco:
        chips_to_give = 4
        score = 13000
    elif three_of_a_kind:
        chips_to_give = 3
        score = 1000 * roll[0]
    elif roll == loco:
        chips_to_give = 2
        score = 900
    else:
        chips_to_give = 1
        score = calculate_score(roll)
    return chips_to_give, score


def computer_roll(computer_name, max_rolls, other_scores):
    rolls = 0
    computer_roll = random_dice_combination()
    print(f"""{computer_name}'s roll:{computer_roll}""")
    print_dice(computer_roll)
    rolls += 1
    chips_to_give, computer_score = analyze_roll(computer_roll)
    while rolls < max_rolls:
        if all(computer_score < scores for scores in other_scores):
            print(f"{computer_name} has chosen to roll again!")
            computer_roll = random_dice_combination()
            print(f"""New roll: {computer_roll}""")
            print_dice(computer_roll)
            rolls += 1
            chips_to_give, computer_score = analyze_roll(computer_roll)
            
        else:
            print(f"{computer_name} has chosen to stop rolling")
            break
            

    return computer_roll, rolls, computer_score


def computer1_turn(max_rolls,other_scores):
    computer1_roll, rolls, computer1_score = computer_roll("computer1", max_rolls,other_scores)
    computer1_chips, computer1_score = analyze_roll(computer1_roll)
    print(f"Computer1 has a score of {computer1_score}")
    return computer1_roll, computer1_chips, computer1_score, rolls


def computer2_turn(max_rolls,other_scores):
    computer2_roll, rolls,computer2_score  = computer_roll("computer2", max_rolls,other_scores)
    computer2_chips, computer2_score = analyze_roll(computer2_roll)
    print(f"Computer2 has a score of {computer2_score}")
    return computer2_roll, computer2_chips, computer2_score, rolls


def computer3_turn(max_rolls,other_scores):
    computer3_roll, rolls, computer3_score  = computer_roll("computer3", max_rolls, other_scores)
    computer3_chips, computer3_score = analyze_roll(computer3_roll)
    print(f"Computer3 has a score of {computer3_score}")
    return computer3_roll, computer3_chips, computer3_score, rolls


def player_turn(max_rolls):
    player_roll = random_dice_combination()
    rolls = 1
    print(f"Your first roll is {player_roll}")
    print_dice(player_roll)
    while rolls < max_rolls:
        roll_again = input("Would you like to roll again? ")
        if roll_again.lower().strip('!') in ['yes','yup','yeah','sure','y']:
            print("You have chosen to roll again!")
            player_roll = random_dice_combination()
            print(f"""New roll:{player_roll}""")
            print_dice(player_roll)
            rolls += 1
        else:
            print("You have chosen to stop rolling")
            break

    print(f"Your final roll is {player_roll}")
    player_chips, player_score = analyze_roll(player_roll)
    print(f"Your score is {player_score}")
    return player_roll, player_chips, player_score, rolls


players_dict = {
    "computer1": computer1_turn,
    "computer2": computer2_turn,
    "computer3": computer3_turn,
    player_name: player_turn,
}


def play_game():
    round = 1
    while all(chips > 0 for chips in chip_count.values()):
        print('+'+'-'*9 +'+')
        print(f"| Round {round} |")
        print('+'+'-'*9 +'+')
        print('')
        print("Here are the current chip counts:")
        for player, chips in chip_count.items():
            print(f"{player}: {chips}")
        print('')
        first, second, third, fourth = choose_order()
        players_list = [first, second, third, fourth]
        max_rolls = 3
        other_scores = []
        scores_dict = {}
        chips_dict = {}

        # runs the roll functions for player in players_list:
        for player in players_list:
            print(f"{player}'s turn")
            start_game = players_dict[player]
            if player in ['computer1','computer2','computer3']:
                roll, player_chips, player_score, rolls_chosen = start_game(max_rolls, other_scores)
            else:
                roll, player_chips, player_score, rolls_chosen = start_game(max_rolls)
            max_rolls = rolls_chosen
            print("")
            scores_dict[player] = player_score
            other_scores.append(player_score)
            chips_dict[player] = player_chips
            time.sleep(4) #waits 4 seconds before printing out the next player's turn
            
            

        #prints scores at the end of the round
        print('')
        print(f'''That is the end of round {round}! Here are the scores:''')
        for player, score in scores_dict.items():
            print(f'{player}: {score}')
        scores = []



        #determines who lost the round and who won the round
        for value in scores_dict.values():
            scores.append(value)

        lowest_score = min(scores)

        losers_list = []
        for player, score in scores_dict.items():
            if score == lowest_score:
                losers_list.append(player)

        if len(losers_list) == 1:
            loser = losers_list[0]
            print(f'{losers_list[0]} lost the round')
        else:
            loser = random.choice(losers_list)
            print(f'{loser} lost the round')


        highest_score = max(scores)
        list_of_winners = []
        for player, score in scores_dict.items():
            if score == highest_score:
                list_of_winners.append(player)

        if len(list_of_winners) == 1:
            winner = list_of_winners[0]
            print(f'{winner} won the round')
        else:
            winner = random.choice(list_of_winners)
            print(f'{winner} won the round')

    # determines how many chips to give to the loser
        chips_to_give = chips_dict[winner]
    
    #subtracts chips from winners and gives chips to loser
        for player in chip_count:
            if player == loser:
                chip_count[player] += chips_to_give
            else:
                chip_count[player] -= chips_to_give
        
        print('')
        print("Here are the updated chip counts:")
        for player, chips in chip_count.items():
            print(f"{player}: {chips}")
            
        round += 1
    print('')
    winners_list = []
    for player, chips in chip_count.items():
        if chips <= 0:
            winners_list.append(player)
            if len(winners_list) == 1:
                print(f'{winners_list[0]} won the game!')
            else:
                winner = random.choice(winners_list)
                print(f'{winner} won the game!')
    print('Game over')






def main():
    play_game()



main()